### ISSUE TITLE
After 100 times i'm always getting an ERROR!

### ISSUE THREAD

**Issue by ghaliahmed** [stefan-jansen/zipline-reloaded#123] opened 2022-07-29 10:36 UTC
Dear Zipline Maintainers,

i'm very happy to write to you :)
after installing all this packages:

  alembic            conda-forge/noarch::alembic-1.8.1-pyhd8ed1ab_0
  bcolz-zipline      ml4t/win-64::bcolz-zipline-1.2.4-py38he6999da_0
  blas               pkgs/main/win-64::blas-1.0-mkl
  blosc              conda-forge/win-64::blosc-1.21.1-h74325e0_3
  bottleneck         conda-forge/win-64::bottleneck-1.3.5-py38hbdcd294_0
  brotlipy           conda-forge/win-64::brotlipy-0.7.0-py38h294d835_1004
  bzip2              conda-forge/win-64::bzip2-1.0.8-h8ffe710_4
  ca-certificates    conda-forge/win-64::ca-certificates-2022.6.15-h5b45459_0
  cached-property    conda-forge/noarch::cached-property-1.5.2-hd8ed1ab_1
  cached_property    conda-forge/noarch::cached_property-1.5.2-pyha770c72_1
  certifi            conda-forge/win-64::certifi-2022.6.15-py38haa244fe_0
  cffi               conda-forge/win-64::cffi-1.15.1-py38hd8c33c5_0
  charset-normalizer conda-forge/noarch::charset-normalizer-2.1.0-pyhd8ed1ab_0
  click              conda-forge/win-64::click-8.1.3-py38haa244fe_0
  colorama           conda-forge/noarch::colorama-0.4.5-pyhd8ed1ab_0
  cryptography       conda-forge/win-64::cryptography-37.0.4-py38hb7941b4_0
  empyrical-reloaded ml4t/win-64::empyrical-reloaded-0.5.8-py38_0
  exchange-calendars ml4t/win-64::exchange-calendars-3.3-py38_0
  greenlet           conda-forge/win-64::greenlet-1.1.2-py38h885f38d_2
  h5py               conda-forge/win-64::h5py-3.7.0-nompi_py38hc790250_100
  hdf5               conda-forge/win-64::hdf5-1.12.1-nompi_h2a0e4a3_104
  idna               conda-forge/noarch::idna-3.3-pyhd8ed1ab_0
  importlib-metadata conda-forge/win-64::importlib-metadata-4.11.4-py38haa244fe_0
  importlib_resourc~ conda-forge/noarch::importlib_resources-5.9.0-pyhd8ed1ab_0
  intel-openmp       conda-forge/win-64::intel-openmp-2022.1.0-h57928b3_3787
  intervaltree       conda-forge/noarch::intervaltree-3.0.2-py_0
  iso3166            conda-forge/noarch::iso3166-2.1.1-pyhd8ed1ab_0
  iso4217            conda-forge/noarch::iso4217-1.9.20220401-pyhd8ed1ab_0
  korean_lunar_cale~ conda-forge/noarch::korean_lunar_calendar-0.2.1-pyh9f0ad1d_0
  krb5               conda-forge/win-64::krb5-1.19.3-h1176d77_0
  libblas            conda-forge/win-64::libblas-3.9.0-12_win64_mkl
  libcblas           conda-forge/win-64::libcblas-3.9.0-12_win64_mkl
  libcurl            conda-forge/win-64::libcurl-7.83.1-h789b8ee_0
  libffi             conda-forge/win-64::libffi-3.4.2-h8ffe710_5
  libiconv           conda-forge/win-64::libiconv-1.16-he774522_0
  liblapack          conda-forge/win-64::liblapack-3.9.0-12_win64_mkl
  libssh2            conda-forge/win-64::libssh2-1.10.0-h680486a_2
  libxml2            conda-forge/win-64::libxml2-2.9.14-hf5bbc77_3
  libxslt            conda-forge/win-64::libxslt-1.1.35-h34f844d_0
  libzlib            conda-forge/win-64::libzlib-1.2.12-h8ffe710_2
  logbook            ml4t/win-64::logbook-1.5.3-py38_0
  lru-dict           conda-forge/win-64::lru-dict-1.1.8-py38h294d835_0
  lxml               conda-forge/win-64::lxml-4.9.1-py38h294d835_0
  lz4-c              conda-forge/win-64::lz4-c-1.9.3-h8ffe710_1
  m2w64-gcc-libgfor~ conda-forge/win-64::m2w64-gcc-libgfortran-5.3.0-6
  m2w64-gcc-libs     conda-forge/win-64::m2w64-gcc-libs-5.3.0-7
  m2w64-gcc-libs-co~ conda-forge/win-64::m2w64-gcc-libs-core-5.3.0-7
  m2w64-gmp          conda-forge/win-64::m2w64-gmp-6.1.0-2
  m2w64-libwinpthre~ conda-forge/win-64::m2w64-libwinpthread-git-5.0.0.4634.697f757-2
  mako               conda-forge/noarch::mako-1.2.1-pyhd8ed1ab_0
  markupsafe         conda-forge/win-64::markupsafe-2.1.1-py38h294d835_1
  mkl                conda-forge/win-64::mkl-2021.4.0-h0e2418a_729
  mkl-service        conda-forge/win-64::mkl-service-2.4.0-py38h4f8af0f_0
  msys2-conda-epoch  conda-forge/win-64::msys2-conda-epoch-20160418-1
  multipledispatch   conda-forge/noarch::multipledispatch-0.6.0-py_0
  multitasking       conda-forge/noarch::multitasking-0.0.9-pyhd8ed1ab_0
  networkx           conda-forge/noarch::networkx-2.8.5-pyhd8ed1ab_0
  numexpr            pkgs/main/win-64::numexpr-2.8.3-py38hb80d3ca_0
  numpy              conda-forge/win-64::numpy-1.23.1-py38h223ccf5_0
  openssl            conda-forge/win-64::openssl-1.1.1q-h8ffe710_0
  packaging          conda-forge/noarch::packaging-21.3-pyhd8ed1ab_0
  pandas             conda-forge/win-64::pandas-1.4.3-py38hcc40339_0
  pandas-datareader  conda-forge/noarch::pandas-datareader-0.10.0-pyh6c4a22f_0
  patsy              conda-forge/noarch::patsy-0.5.2-pyhd8ed1ab_0
  pip                conda-forge/noarch::pip-22.2.1-pyhd8ed1ab_0
  pycparser          conda-forge/noarch::pycparser-2.21-pyhd8ed1ab_0
  pyluach            conda-forge/noarch::pyluach-2.0.0-pyhd8ed1ab_0
  pyopenssl          conda-forge/noarch::pyopenssl-22.0.0-pyhd8ed1ab_0
  pyparsing          conda-forge/noarch::pyparsing-3.0.9-pyhd8ed1ab_0
  pysocks            conda-forge/win-64::pysocks-1.7.1-py38haa244fe_5
  pytables           conda-forge/win-64::pytables-3.7.0-py38h7deab4d_0
  python             conda-forge/win-64::python-3.8.13-h9a09f29_0_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0
  python-interface   conda-forge/noarch::python-interface-1.6.0-py_0
  python_abi         conda-forge/win-64::python_abi-3.8-2_cp38
  pytz               conda-forge/noarch::pytz-2022.1-pyhd8ed1ab_0
  requests           conda-forge/noarch::requests-2.28.1-pyhd8ed1ab_0
  scipy              conda-forge/win-64::scipy-1.8.1-py38h4990095_2
  setuptools         conda-forge/win-64::setuptools-63.2.0-py38haa244fe_0
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  snappy             conda-forge/win-64::snappy-1.1.9-h82413e6_1
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.4.0-pyhd8ed1ab_0
  sqlalchemy         conda-forge/win-64::sqlalchemy-1.4.39-py38h294d835_0
  sqlite             conda-forge/win-64::sqlite-3.39.2-h8ffe710_0
  statsmodels        conda-forge/win-64::statsmodels-0.13.2-py38hbdcd294_0
  ta-lib             ml4t/win-64::ta-lib-0.4.21-py38hb572761_0
  tbb                conda-forge/win-64::tbb-2021.5.0-h2d74725_1
  tk                 conda-forge/win-64::tk-8.6.12-h8ffe710_0
  toolz              conda-forge/noarch::toolz-0.12.0-pyhd8ed1ab_0
  trading-calendars  conda-forge/noarch::trading-calendars-2.1.1-pyhd3deb0d_0
  ucrt               conda-forge/win-64::ucrt-10.0.20348.0-h57928b3_0
  urllib3            conda-forge/noarch::urllib3-1.26.11-pyhd8ed1ab_0
  vc                 conda-forge/win-64::vc-14.2-hb210afc_6
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.29.30037-h902a5da_6
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  win_inet_pton      conda-forge/win-64::win_inet_pton-1.1.0-py38haa244fe_4
  xz                 conda-forge/win-64::xz-5.2.5-h62dcd97_1
  yfinance           ml4t/noarch::yfinance-0.1.63-py_0
  zipline-reloaded   ml4t/win-64::zipline-reloaded-2.2.0-py38he6999da_0
  zipp               conda-forge/noarch::zipp-3.8.0-pyhd8ed1ab_0
  zlib               conda-forge/win-64::zlib-1.2.12-h8ffe710_2
  zstd               conda-forge/win-64::zstd-1.5.2-h6255e5f_2

Proceed ([y]/n)? y

#################### this is my error! ################################""

(z_39) C:\Users\GHALI>python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:45) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from zipline.api import order_target, record, symbol
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\GHALI\anaconda3\envs\z_39\lib\site-packages\zipline\__init__.py", line 29, in <module>
    from .utils.run_algo import run_algorithm
  File "C:\Users\GHALI\anaconda3\envs\z_39\lib\site-packages\zipline\utils\run_algo.py", line 24, in <module>
    from zipline.pipeline.data import USEquityPricing
  File "C:\Users\GHALI\anaconda3\envs\z_39\lib\site-packages\zipline\pipeline\__init__.py", line 1, in <module>
    from .classifiers import Classifier, CustomClassifier
  File "C:\Users\GHALI\anaconda3\envs\z_39\lib\site-packages\zipline\pipeline\classifiers\__init__.py", line 1, in <module>
    from .classifier import (
  File "C:\Users\GHALI\anaconda3\envs\z_39\lib\site-packages\zipline\pipeline\classifiers\classifier.py", line 22, in <module>
    from zipline.pipeline.term import ComputableTerm
  File "C:\Users\GHALI\anaconda3\envs\z_39\lib\site-packages\zipline\pipeline\term.py", line 45, in <module>
    from .domain import Domain, GENERIC, infer_domain
  File "C:\Users\GHALI\anaconda3\envs\z_39\lib\site-packages\zipline\pipeline\domain.py", line 27, in <module>
    from zipline.country import CountryCode
  File "C:\Users\GHALI\anaconda3\envs\z_39\lib\site-packages\zipline\country.py", line 10, in <module>
    class CountryCode(object):
  File "C:\Users\GHALI\anaconda3\envs\z_39\lib\site-packages\zipline\country.py", line 55, in CountryCode
    TURKEY = code("TURKEY")
  File "C:\Users\GHALI\anaconda3\envs\z_39\lib\site-packages\zipline\country.py", line 7, in code
    return countries_by_name[name].alpha2
KeyError: 'TURKEY'

**Comment by RichardDale** [comment] 2022-07-29 10:41
Duplicate of #114  - Workaround is shown there.

**Comment by ghaliahmed** [comment] 2022-07-29 10:57
Dear RichardDale,
i don't know how to thank you...... **THANK YOU VERY MUCH**

**Comment by RichardDale** [comment] 2022-07-29 11:20
Send lambo

**Comment by stefan-jansen** [comment] 2022-11-03 20:47
Addressed by #117 .

**Closed by stefan-jansen** 2022-11-03 20:47 UTC
