### ISSUE TITLE
execute order at next bar‘s open price

### ISSUE THREAD

**Issue by quant2008** [stefan-jansen/zipline-reloaded#235] opened 2023-12-17 04:51 UTC
Hello, [this post ](https://github.com/quantopian/zipline/pull/1512) shows how to Add slippage models to execute order at next bar's open price. I wonder if this solution is correct and if it is implemented in zipline-reloaded?

**Comment by gnzsnz** [comment] 2024-04-23 12:09
i'm interested in the possibility of having orders at open price

**Comment by stefan-jansen** [comment] 2024-09-26 14:35
Appears to be duplicate of #132; PRs are always welcome.

**Closed by stefan-jansen** 2024-09-26 14:35 UTC
