### ISSUE TITLE
Unable to use the latest Zipline

### ISSUE THREAD

**Issue by quantltq** [stefan-jansen/zipline-reloaded#121] opened 2022-07-28 11:01 UTC
Dear Zipline Maintainers,

<details>

* Operating System:  windows 10
* Python Version: `Python 3.7.13`
* Python Bitness: 
* How did you install Zipline:  `conda`
* Python packages: `$ pip freeze` or `$ conda list`

</details>
1.  I used the following command to install
"C:\Users\Administrator>conda install -c ml4t -c conda-forge -c ranaroussi zipline-reloaded"
2、I then tried to command zipline with an error。

(base) C:\Users\Administrator>zipline
Traceback (most recent call last):
  File "d:\Anaconda3\Scripts\zipline-script.py", line 6, in <module>
    from zipline.__main__ import main
  File "d:\Anaconda3\lib\site-packages\zipline\__init__.py", line 29, in <module>
    from .utils.run_algo import run_algorithm
  File "d:\Anaconda3\lib\site-packages\zipline\utils\run_algo.py", line 24, in <module>
    from zipline.pipeline.data import USEquityPricing
  File "d:\Anaconda3\lib\site-packages\zipline\pipeline\__init__.py", line 1, in <module>
    from .classifiers import Classifier, CustomClassifier
  File "d:\Anaconda3\lib\site-packages\zipline\pipeline\classifiers\__init__.py", line 1, in <module>
    from .classifier import (
  File "d:\Anaconda3\lib\site-packages\zipline\pipeline\classifiers\classifier.py", line 22, in <module>
    from zipline.pipeline.term import ComputableTerm
  File "d:\Anaconda3\lib\site-packages\zipline\pipeline\term.py", line 45, in <module>
    from .domain import Domain, GENERIC, infer_domain
  File "d:\Anaconda3\lib\site-packages\zipline\pipeline\domain.py", line 27, in <module>
    from zipline.country import CountryCode
  File "d:\Anaconda3\lib\site-packages\zipline\country.py", line 10, in <module>
    class CountryCode(object):
  File "d:\Anaconda3\lib\site-packages\zipline\country.py", line 55, in CountryCode
    TURKEY = code("TURKEY")
  File "d:\Anaconda3\lib\site-packages\zipline\country.py", line 7, in code
    return countries_by_name[name].alpha2
KeyError: 'TURKEY'

Sincerely,
ltq_quant

**Comment by MBounouar** [comment] 2022-07-28 11:27
Duplicate of #117

**Comment by RichardDale** [comment] 2022-07-28 13:59
try adding
iso3166==2.0.2
to your conda cmd line

ie:
`conda install -c ml4t -c conda-forge -c ranaroussi zipline-reloaded iso3166==2.0.2`

**Comment by Okohedeki** [comment] 2022-07-28 23:05
@RichardDale I have been talking with the maintainer over at iso about [this](https://github.com/deactivated/python-iso3166/issues/33). Hopefully, we can get a fix to use non-accented versions soon.

**Comment by RichardDale** [comment] 2022-07-29 10:43
It's easier to install iso3166 v2.0.2 as a workaround and wait for iso3166 devs/zipline-reloaded devs to figure out a better solution.

**Comment by stefan-jansen** [comment] 2022-10-27 16:17
Addressed by #117

**Closed by stefan-jansen** 2022-10-27 16:17 UTC
